name: fyp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter_mjpeg: ^2.0.4
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.11.0
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.0
  get: ^4.6.6
  flutter:
    sdk: flutter
  flutter_vlc_player: ^7.4.1
  webview_flutter: ^4.0.6
  web_socket_channel: ^2.4.0
  flutter_webrtc: ^0.6.8
  http: ^0.13.6
  rtmp_broadcaster: ^2.2.4
  image_picker: ^1.0.8
  url_launcher: ^6.0.3
  video_player: ^2.2.5
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/download.jpg
  - assets/OIG4.jpeg
